name: Send Commit Info to Power Automate

on:
  push:
    branches:
      - main

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email with commit info
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: youraccount@outlook.com
          password: ${{ secrets.OUTLOOK_APP_PASSWORD }}
          subject: "[GitHub Commit] New changes pushed"
          to: youraccount@outlook.com
          from: youraccount@outlook.com
          body: |
            Repository: ${{ github.repository }}
            Pusher: ${{ github.actor }}
            Commit Message: ${{ github.event.head_commit.message }}
            Commit URL: ${{ github.event.head_commit.url }}
